services:
  strmhub:
    image: ghcr.io/daisyyijin/strmhub:latest
    container_name: strmhub
    restart: unless-stopped
    ports:
      - "6060:6060"
      - "6086:6086"
    volumes:
      - ./data:/data
      - ./media:/media
      - ./logs:/logs
    environment:
      - TZ=Asia/Shanghai
